### PR TITLE
WIP: Rewrite

### PR DESCRIPTION
**Pull request by garbles**
Rewriting Yolk because I've learned some shit.

Notable changes will be:
- [x] Use webpack instead of browserify to bundle
- [x] Use mocha + chai + karma instead of tape + tape-run to run tests
- [x] Use rxjs v5
- [x] Use flow for typed code
- [x] Use istanbul for code coverage
- [x] Write a more concise diff algorithm for patching changes (remove virtual-dom in favor of something that directly depends on rxjs)
- [x] You can no longer infinitely nest observables and have Yolk unwrap them. This was a huge performance hit for large objects and large component trees.
- [x] Decouple prop/attribute patching to child node patching.
- [ ] ~~`createEventHandler` as a top-level function?~~ (need to be able to destroy subscriptions)
- [x] `createEventHandler` will be just a wrapper for a Subject. allows anyone to use Subjects as eventhandlers. Wrap Subject in a function if injected as a prop to an event handler.
- [ ] ~~`createCursor` will create an overloaded Subject that will add an additional `refine` method to scope data. Possibly also create a `createContext` which wraps a cursor allowing you access it from where ever in the tree, e.g.~~ (push to a later version)

```js
const createContext = cursor => Component => args => {
    return Component({...args, cursor})
  }
}

const _cursor = createCursor(myInitialState)
const WrappedComponent = createContext(_cursor)(Component)
```

- [ ] Components will be allowed to return observables. This will help with being able to wrap component functions in other functions.
- [ ] ~~move DOM diffing to Web Worker threads~~ (push to a later version. should be pretty easy though)
- [x] Remove behavior where "un-registered" props wouldn't be appended to node.

### CODE REVIEW

**Comment by jadbox** [comment]
Excellent list of changes. Are you sure you want to adopt rxjs v5 when it's not stable yet? I've been told that it's not ready for even simple production use-cases atm.

**Comment by garbles** [comment]
@jadbox I'm anticipating that this will take me longer to complete than RxJS :stuck_out_tongue:

**Comment by jadbox** [comment]
>>  I'm anticipating that this will take me longer to complete than RxJS

Judging by the completed checkboxes, looks like you're pretty close? Do you think you have an eta for the Yolk rewrite, at least in beta form?

**Comment by garbles** [comment]
@jadbox I'm taking a break from writing software in my free time for the moment. I can't give you a date, but I will come back to this soon-ish.

**Comment by geekytime** [comment]
Yay! It looks like you're getting fairly close with the new version!

Is there anything I can do to help you finish up the rewrite? I'm happy to put together merge requests, take a stab at documentation, or whatever. Just tell me what still needs to get done.

(Sorry to blast in out of nowhere, but I just discovered Yolk last week, and it's _clearly_ a better way to build apps than React, and I agree that it's much easier for large apps than Cycle.js. Let's take it to the next level! :+1:)

**Comment by garbles** [comment]
Hi @geekytime,

I've been slowly chipping away at this over the past few months. I'm almost ready to merge what I've done into master and start rebuilding the test suite.

I am VERY interested in help on this project. Documentation is something that I've had a hard time doing and so your help would be appreciated. I will reach out to you again in a week or so (after merging this branch) to see what can be done.

**Pull request merged**
