### PR TITLE
Better distributable

### PR DESCRIPTION
**Pull request by geekytime**
This one [sort of works from JSBin](http://jsbin.com/kazorayeqe/1/edit?html,js,output). 

I had trouble getting [a more complex example](http://jsbin.com/bijacitupu/1/edit?html,js,console,output) to work, but perhaps I am just bad at hyperscript? It seems to me that it's the right type going in there, but maybe this is related to the type-checking problems you discussed in other issues @garbles?

I can rebase and clean up before we merge, but I wanted to get it up where we can play with it.

### CODE REVIEW

**Comment by geekytime** [comment]
[I tried another example](http://jsbin.com/fixaduvovi/5/edit?html,js,console,output) forked from a previous example and updated for the latest build.

This one has the same problems. It appears that I broke something related to how hyperscript is rendering the virtual nodes? It doesn't look like it's properly subscribing to Observable props...

**Comment by geekytime** [comment]
Even [this super-simple example](http://jsbin.com/zoyuyevapo/1/edit?html,js,console,output) doesn't work when we use an observable as content.

**Comment by garbles** [comment]
A few things:
- [This commit](https://github.com/garbles/yolk/commit/21a50ed3048afa521b37802cc8c3604530c0c6a7) fixes the problem of using many versions of RxJS
- The examples you've provided are using RxJS Alpha 8 which is very outdated
- This still doesn't fix the problem of how to add operators to what comes out of `createEventHandler`

**Comment by geekytime** [comment]
> The examples you've provided are using RxJS Alpha 8 which is very outdated

Duh. It works when I update to beta-7.

> This still doesn't fix the problem of how to add operators to what comes out of createEventHandler

If we're using the global UMD build of Rx do we need to add the operators?

**Comment by geekytime** [comment]
Yeah, everything seems to work fine on JSBin now. Here's an [example with "extra" operators](http://jsbin.com/noqaxayofo/edit?html,js,console,output).

I'm still open to ideas about the name/location of the `yolk.min.js` file, and whether an automated integration test using the minified file seems necessary.

**Comment by geekytime** [comment]
I could also add a small section to the readme that shows how to use Yolk from JSBin. It is such a useful way to submit examples of bugs, etc.

**Comment by LongLiveCHIEF** [comment]
Too bad github doesn't do what StackOverflow started doing when you include jsbin's and the like (the execute button)

**Comment by jadbox** [comment]
I'm getting the below error using @geekytime minified builds (haven't been able to use any alternative method yet). I've filed an issue here: https://github.com/garbles/yolk/issues/91
```
Rx.umd.js:13424Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

**Comment by garbles** [comment]
This LGTM with a few notes:

1) Would be nice to have an un-minified build (could push to another PR)
2) Would be nice if you could rebase off of master (specs should pass now)

**Comment by jadbox** [comment]
LGTM

Let's see if we can get this in today as I'm currently using @geekytime older Yolk build for our production :P

**Comment by geekytime** [comment]
> Would be nice if you could rebase off of master (specs should pass now)

Yeah, if you want to avoid the merge commits I can rebase. Just to be clear, you want me to force-push back to this branch, right? You're okay with me rewriting history?

**Comment by garbles** [comment]
@geekytime

**Comment by geekytime** [comment]
Er. I guess I did that wrong. My git-fu is not strong, today. 😒

**Comment by geekytime** [comment]
Something I did in git ticked off github, and it closed this automatically. I opened #94 instead.

I apologize for my lack of inter-fork rebasing skills.

**Comment by geekytime** [comment]
> Let's see if we can get this in today as I'm currently using @geekytime older Yolk build for our production :P

Sorry if my branch problems caused you any headaches. If you need a stopgap until #94 gets merged, you can use: https://rawgit.com/StateFarmIns/yolk/add-browser-distributable/dist/yolk.min.js

**Comment by LongLiveCHIEF** [comment]
> I apologize for my lack of inter-fork rebasing skills.

emperor displeased

**Comment by garbles** [comment]
👏

**Pull request closed without merging**
