### PR TITLE
basic one-file distribution

### LINKED ISSUE #84: Is there still a distribution being published for use from JSBin?
It looks like there maybe used to be a distribution we could access through rawgit, but it's not there anymore. I didn't see anything in the current build that looks like that dist file.

### PR DESCRIPTION
**Pull request by geekytime**
I tested this by replacing references to "yolk" in my app to the file path of the new distributable, and everything worked fine.

Let me know if you have any ideas on how we could test this better as part of the build process.

Fixes #84

### CODE REVIEW

**Comment by garbles** [comment]
How does this work with all of those external dependencies?

**Comment by geekytime** [comment]
I should have mentioned that this will currently only work in a webpack-style environment. I probably shouldn't have marked that it would fix the JSBin issue, now that I think about it. I just wanted to get this posted to get the discussion started.

Building a single build for use in JSBin or web environements is going to be a problem because of how rxjs modularized their code. In cases like `createEventHandler`, we're going to hand applications an Observable that may not have the operators on it that they need, unless we can convince webpack to use a global namespaced `rxjs` instead of a modular `rxjs`. 

I'll keep digging into it.

**Comment by geekytime** [comment]
Do you think we should focus on a build that _includes_ all/most dependencies? Or one that assumes dependencies will be available, either via webpack, or as globals in a browser environment?

**Comment by garbles** [comment]
FWIW, RxJS5 uses a [symbol to determine if something is an observable](https://www.npmjs.com/package/symbol-observable). If an object has the observable symbol as a property and a subscribe method, it can be consumed. i.e. You can use two different instances of RxJS together and they will be compatible.

I need to make a change to the `isObservable` module to properly reflect this. Once that's done, you should be able to just build Yolk as is without any externals and it should just work in JSBin.

(I can probably do this work tonight and then pull in your changes here!)

**Comment by garbles** [comment]
Scratch that. The observable created by the createEventHandler wouldn't work properly.. I see what you mean.

**Comment by geekytime** [comment]
After thinking through it some more, I think I will have to tell Webpack how to find all of the individual rxjs objects as global objects. I'll experiment with that a bit.

I'll also need to export a global Yolk variable, or we won't be able to access Yolk itself. 😜 

Jeez. I forgot how annoying web development was before Browserify and Webpack...

**Comment by geekytime** [comment]
It looks like Angular has a strategy for handling this exact problem: https://github.com/angular/angular/blob/master/gulpfile.js#L1304

Webpack's `external`s can apparently specify environment-specific ways to find a module. I'm going to look into doing that.

**Comment by garbles** [comment]
SGTM!

**Comment by geekytime** [comment]
Closing in favor of #88

**Pull request closed without merging**
